# ============================================
# Local 환경 설정 (개발용 - Docker MySQL)
# ============================================

# Spring Boot 설정
spring:
  # JPA/Hibernate 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # Flyway가 스키마 관리
    properties:
      hibernate:
        format_sql: true     # 로컬: SQL 포맷팅
    show-sql: true           # 로컬: SQL 로그 출력
  
  # Kafka Consumer 설정 (Local 환경)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: local-dispatch-event-consumer
#      auto-offset-reset: earliest
#      enable-auto-commit: false
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "vroong.laas.dispatch.*"

# Local DataSource (Writer/Reader 동일 - localhost:3306)
dispatch:
  datasource:
    # Writer DataSource (Local - localhost)
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/dispatch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${DB_USERNAME:dispatch_user}
      password: ${DB_PASSWORD:dispatch_password}
      hikari:
        pool-name: DispatchWriterPool
        maximum-pool-size: 5  # 로컬: 작은 Pool
        minimum-idle: 2
        connection-timeout: 3000
        idle-timeout: 600000
        max-lifetime: 1800000
    
    # Reader DataSource (Local - localhost, Writer와 동일)
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/dispatch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      username: ${DB_USERNAME:dispatch_user}
      password: ${DB_PASSWORD:dispatch_password}
      hikari:
        pool-name: DispatchReaderPool
        maximum-pool-size: 10  # 로컬: 조회용으로 조금 더 크게
        minimum-idle: 2
        connection-timeout: 3000
        idle-timeout: 600000
        max-lifetime: 1800000

# Actuator 설정 (Local 환경 - 개발 편의)
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 로컬: 모든 엔드포인트 노출 (개발/디버깅 용이)
  
  endpoint:
    health:
      show-details: always  # 로컬: 항상 Health Check 상세 정보 노출


# Kafka/Outbox 설정 (Local 환경)
outbox:
  event:
    publisher:
      bootstrap-servers: localhost:9092  # 로컬 Kafka (실제 연결 안 해도 Bean 생성용)
      enabled: true

# 로그 설정
logging:
  level:
    vroong.laas.dispatch: DEBUG  # 로컬: 상세 로그
    org.hibernate.SQL: DEBUG
